import type { Category, Problem } from '../types';
import { datasets } from './datasets';

export const categories = {
  energy: {
    name: 'Energy & Transportation',
    colour: 'oklch(88.5% 0.062 18.334)',
  },
  synth: {
    name: 'Synthetic',
    colour: 'oklch(95.1% 0.026 236.824)',
  },
  svm: {
    name: 'Machine Learning / Support Vector Machine',
    colour: 'oklch(95% 0.052 163.051)',
  },
  regression: {
    name: 'Machine Learning / Regression',
    colour: 'oklch(95.2% 0.037 318.852)',
  },
} satisfies Record<string, Category>;

export const problems: Problem[] = [
  {
    name: 'Transmission station',
    category: categories.energy,
    upperLevelVariables: 10,
    lowerLevelVariables: 600,
    upperLevelConstraints: 0,
    lowerLevelConstraints: 10,
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'Ajay et al.',
      year: 2004,
      link: 'https://example.com',
    },
    datasets: [datasets[3]!, datasets[2]!, datasets[7]!],
  },
  {
    name: 'Electric power markets',
    category: categories.energy,
    upperLevelVariables: 5,
    lowerLevelVariables: 150,
    upperLevelConstraints: 5,
    lowerLevelConstraints: 10,
    addedAt: new Date('2025-03-12'),
    citation: {
      authors: 'Gabriel',
      year: 2010,
      link: 'https://example.com',
    },
    datasets: [datasets[2]!, datasets[0]!, datasets[5]!],
  },
  {
    name: 'weish26.dat-100',
    category: categories.synth,
    upperLevelVariables: 700,
    lowerLevelVariables: 700,
    upperLevelConstraints: 15,
    lowerLevelConstraints: 94,
    addedAt: new Date('2025-03-12'),
  },
  {
    name: 'BCPIns',
    category: categories.synth,
    upperLevelVariables: 100,
    lowerLevelVariables: 1593,
    upperLevelConstraints: 0,
    lowerLevelConstraints: 512,
    addedAt: new Date('2023-10-01'),
  },
  {
    name: 'normalClique',
    category: categories.synth,
    upperLevelVariables: 2,
    lowerLevelVariables: 236,
    upperLevelConstraints: 10,
    lowerLevelConstraints: 236,
    addedAt: new Date('2023-10-01'),
  },
  {
    name: 'Linear',
    category: categories.svm,
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2020-07-05'),
    citation: {
      authors: 'Moore.',
      year: 2007,
      link: 'https://example.com',
    },
  },
  {
    name: 'Linear regularised',
    category: categories.svm,
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2025-03-12'),
    citation: {
      authors: 'Moore.',
      year: 2007,
      link: 'https://example.com',
    },
  },
  {
    name: 'RBF kernel',
    category: categories.svm,
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'Coniglio et al.',
      year: 2022,
      link: 'https://example.com',
    },
  },
  {
    name: 'Polynomial kernel',
    category: categories.svm,
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'Kunapuli et al.',
      year: 2020,
      link: 'https://example.com',
    },
  },
  {
    name: 'Simple Linear',
    category: categories.regression,
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'citation.',
      year: 2020,
      link: 'https://example.com',
    },
  },
  {
    name: 'Multiple Linear',
    category: categories.regression,
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'citation.',
      year: 2020,
      link: 'https://example.com',
    },
  },
  {
    name: 'Polynomial',
    category: categories.regression,
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'citation.',
      year: 2020,
      link: 'https://example.com',
    },
  },
  {
    name: 'Lasso',
    category: categories.regression,
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'citation.',
      year: 2020,
      link: 'https://example.com',
    },
  },
  {
    name: 'Ridge',
    category: categories.regression,
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'citation.',
      year: 2020,
      link: 'https://example.com',
    },
  },
];
