import type { Problem } from '../types';

export const problems: Problem[] = [
  {
    name: 'Transmission station',
    category: 'Energy & Transportation',
    upperLevelVariables: 10,
    lowerLevelVariables: 600,
    upperLevelConstraints: 0,
    lowerLevelConstraints: 10,
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'Ajay et al.',
      year: 2004,
      link: 'https://example.com',
    },
  },
  {
    name: 'Electric power markets',
    category: 'Energy & Transportation',
    upperLevelVariables: 5,
    lowerLevelVariables: 150,
    upperLevelConstraints: 5,
    lowerLevelConstraints: 10,
    addedAt: new Date('2025-03-12'),
    citation: {
      authors: 'Gabriel',
      year: 2010,
      link: 'https://example.com',
    },
  },
  {
    name: 'weish26.dat-100',
    category: 'Synthetic',
    upperLevelVariables: 700,
    lowerLevelVariables: 700,
    upperLevelConstraints: 15,
    lowerLevelConstraints: 94,
    addedAt: new Date('2025-03-12'),
  },
  {
    name: 'BCPIns',
    category: 'Synthetic',
    upperLevelVariables: 100,
    lowerLevelVariables: 1593,
    upperLevelConstraints: 0,
    lowerLevelConstraints: 512,
    addedAt: new Date('2023-10-01'),
  },
  {
    name: 'normalClique',
    category: 'Synthetic',
    upperLevelVariables: 2,
    lowerLevelVariables: 236,
    upperLevelConstraints: 10,
    lowerLevelConstraints: 236,
    addedAt: new Date('2023-10-01'),
  },
  {
    name: 'Linear',
    category: 'Machine Learning / Support Vector Machine',
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2020-07-05'),
    citation: {
      authors: 'Moore.',
      year: 2007,
      link: 'https://example.com',
    },
  },
  {
    name: 'Linear regularised',
    category: 'Machine Learning / Support Vector Machine',
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2025-03-12'),
    citation: {
      authors: 'Moore.',
      year: 2007,
      link: 'https://example.com',
    },
  },
  {
    name: 'RBF kernel',
    category: 'Machine Learning / Support Vector Machine',
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'Coniglio et al.',
      year: 2022,
      link: 'https://example.com',
    },
  },
  {
    name: 'Polynomial kernel',
    category: 'Machine Learning / Support Vector Machine',
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'Kunapuli et al.',
      year: 2020,
      link: 'https://example.com',
    },
  },
  {
    name: 'Simple Linear',
    category: 'Machine Learning / Regression',
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'citation.',
      year: 2020,
      link: 'https://example.com',
    },
  },
  {
    name: 'Multiple Linear',
    category: 'Machine Learning / Regression',
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'citation.',
      year: 2020,
      link: 'https://example.com',
    },
  },
  {
    name: 'Polynomial',
    category: 'Machine Learning / Regression',
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'citation.',
      year: 2020,
      link: 'https://example.com',
    },
  },
  {
    name: 'Lasso',
    category: 'Machine Learning / Regression',
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'citation.',
      year: 2020,
      link: 'https://example.com',
    },
  },
  {
    name: 'Ridge',
    category: 'Machine Learning / Regression',
    upperLevelVariables: '10-80000',
    lowerLevelVariables: '10-80000',
    upperLevelConstraints: '10-80000',
    lowerLevelConstraints: '10-80000',
    addedAt: new Date('2023-10-01'),
    citation: {
      authors: 'citation.',
      year: 2020,
      link: 'https://example.com',
    },
  },
];
